/**
 * Seed campaigns with PAS / number-led hooks (marketing-skills patterns).
 * Browser-safe export used by campaign-store.
 */

import type { Campaign } from "../db/schema/campaigns";

const now = new Date().toISOString();

/** Seed data — in production this inserts into Postgres via Drizzle */
export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-helix-onboard",
    projectId: "proj-helix",
    slug: "helix-first-stake",
    title: "Stake your first SOL on Helix",
    hook: "Cut your staking setup from 3 tools to 1 click — earn on day one.",
    description:
      "Problem: juggling explorers, wallets, and validators. Agitate: missed epochs and idle SOL. Solve: complete Helix’s guided stake flow and claim a protocol reward.",
    objective: "activation",
    status: "active",
    priority: "override",
    zones: ["discover", "journey", "project"],
    category: "staking",
    budgetLamports: 50_000_000_000,
    spentLamports: 2_500_000_000,
    rewardPerCompletionLamports: 50_000_000,
    maxCompletions: 1000,
    completionCount: 50,
    tasks: [
      {
        id: "t1",
        type: "visit",
        title: "Open Helix stake UI",
        description: "Visit the official Helix staking page from Discover.",
        rewardLamports: 10_000_000,
      },
      {
        id: "t2",
        type: "quiz",
        title: "Epoch basics",
        description: "Answer 3 questions on epochs and commission.",
        rewardLamports: 15_000_000,
      },
      {
        id: "t3",
        type: "onchain",
        title: "Stake ≥ 0.1 SOL",
        description: "Submit a real stake instruction; we verify on-chain.",
        rewardLamports: 25_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "camp-quarry-liq",
    projectId: "proj-quarry",
    slug: "quarry-provide-liquidity",
    title: "Provide liquidity on Quarry",
    hook: "Still earning 0% on idle USDC? Route it into Quarry in under 5 minutes.",
    description:
      "Add liquidity to a Quarry pool and earn protocol incentives. On-chain deposit verified via Helius.",
    objective: "liquidity",
    status: "active",
    priority: "contract",
    zones: ["discover", "project"],
    category: "defi",
    budgetLamports: 80_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 80_000_000,
    maxCompletions: 500,
    completionCount: 0,
    tasks: [
      {
        id: "t1",
        type: "visit",
        title: "Open Quarry pools",
        description: "Browse live pools from Discover.",
        rewardLamports: 20_000_000,
      },
      {
        id: "t2",
        type: "onchain",
        title: "Deposit liquidity",
        description: "Deposit into any Quarry pool; signature verified on-chain.",
        rewardLamports: 60_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "camp-signal-edu",
    projectId: "proj-signal",
    slug: "signal-oracle-101",
    title: "Oracle 101 with Signal",
    hook: "47% of failed liquidations start with stale prices — learn how Signal keeps feeds live.",
    description:
      "Short education path on oracle design, then a verified read from Signal’s demo feed.",
    objective: "education",
    status: "active",
    priority: "contract",
    zones: ["discover", "journey"],
    category: "education",
    budgetLamports: 20_000_000_000,
    spentLamports: 1_000_000_000,
    rewardPerCompletionLamports: 25_000_000,
    maxCompletions: 800,
    completionCount: 40,
    tasks: [
      {
        id: "t1",
        type: "quiz",
        title: "Stale price quiz",
        description: "3 questions on oracle freshness.",
        rewardLamports: 10_000_000,
      },
      {
        id: "t2",
        type: "onchain",
        title: "Read Signal feed",
        description: "Call the demo program and submit the tx signature.",
        rewardLamports: 15_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "camp-northwind-discover",
    projectId: "proj-northwind",
    slug: "northwind-markets",
    title: "Explore Northwind markets",
    hook: "Browse live markets — no deposit required to learn the UI.",
    description: "Organic discovery fill for Northwind. Low reward, high volume.",
    objective: "discovery",
    status: "active",
    priority: "remnant",
    zones: ["discover", "lend_teaser"],
    category: "markets",
    budgetLamports: 10_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 5_000_000,
    maxCompletions: 2000,
    completionCount: 0,
    tasks: [
      {
        id: "t1",
        type: "visit",
        title: "Open markets page",
        description: "Visit Northwind markets from Discover.",
        rewardLamports: 5_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "camp-draft-example",
    projectId: "proj-lumen",
    slug: "lumen-pending",
    title: "Lumen retention sprint",
    hook: "Win back wallets that tried Lumen once — 2x reward this week only.",
    description: "Draft example for the advertise UI (pending_review path).",
    objective: "retention",
    status: "pending_review",
    priority: "contract",
    zones: ["project", "discover"],
    category: "payments",
    budgetLamports: 40_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 40_000_000,
    maxCompletions: 400,
    completionCount: 0,
    tasks: [
      {
        id: "t1",
        type: "onchain",
        title: "Complete one Lumen payment",
        description: "Any merchant demo payment ≥ 0.01 SOL equivalent.",
        rewardLamports: 40_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
